ARG BASE_IMAGE="ghcr.io/gbraad-devenv/opensuse-golang/base"
ARG BASE_VERSION="latest"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/opensuse-golang"

USER gbraad

ENTRYPOINT [ "/bin/zsh" ]
