ARG BASE_IMAGE="ghcr.io/gbraad-devenv/opensuse/base"
ARG BASE_VERSION="latest"

FROM ${BASE_IMAGE}:${BASE_VERSION}

USER root

RUN zypper install -y \
        go \
        delve \
    && zypper clean -a
