name: build process
run-name: Build process

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  build-and-push-base:
    name: Build and push - openSUSE Golang container
    uses: ./.github/workflows/reusable-build-and-push-container.yml
    with:
      container_name: "base"
    secrets: inherit
